apiVersion: apps/v1 #mengunnakan apps kubernetes dengan versi api v1
kind: Deployment #menggunakan object deployment
metadata: #parameter untuk mendefinsikan objeck
  name: karsajobs-backend # Nama pods yang akan digunakan
  labels: #label pada object deployment
    app: karsajobs # menggunakan label dengan app karsajobs
    tier: backend # menggunakan label dengan tier backend
spec: # tempat untuk menspesifikasikan resource
  replicas: 1 #untuk menentukan jumlah replicas
  selector: #selector pada spec
    matchLabels: #menggunakan selector dengan mathLabels
      tier: backend #menggunakan tier backend
  template: # template untuk spec
    metadata: #parameter untuk mendefinisikan object
      labels: #label pada spec
        app: karsajobs #menggunakan label dengan nama app karsajobs
        tier: backend #menggunkan label dengan nama tier backend
    spec: #spec pada template
      containers: # menggunakan container untuk object deployment
      - name: karsajobs-backend #nama yang akan digunakan oleh object
        image: ghcr.io/rachmandev/karsajobs:latest # menggunakan docker image karsajobs-ui yang di ambil dari github packages
        ports: # port pada container
          - containerPort: 8080 #port yang akan digunakan aplikasi
        env: #environment untuk aplikasi
          - name: APP_PORT #environment variable yang akan digunakan aplikasi
            value: "8080" #port yang akan digunakan aplikasi
          - name: MONGO_HOST #environment variable yang akan digunakan aplikasi
            value: mongodb #host yanga akan digunakan aplikas dengan value mongodb diambil dari service mongodb
          - name: MONGO_USER #environment variable yang akan digunakan aplikasi
            valueFrom: #untuk mengambil value user untuk MONGO_USER
              secretKeyRef: #untuk mengambil value
                name: mongo-secret #mengambil value/data dari object Secret
                key: MONGO_ROOT_USERNAME #Value PasswUsername di ambil dari MONGO_ROOT_USERNAME
          - name: MONGO_PASS #environment variable yang akan digunakan aplikasi
            valueFrom: #untuk mengambil value user untuk MONGO_PASS
              secretKeyRef: #untuk mengambil value
                name: mongo-secret #mengambil value/data dari object Secret
                key: MONGO_ROOT_PASSWORD #Value Password di ambil dari MONGO_ROOT_PASSWORD