version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          docker build -t CircleCI-Public/karsajobs:latest .
  lint:
    docker:
      - image: golangci/golangci-lint:v1.37-alpine
    steps:
      - checkout
      - run: golangci-lint run
  test:
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    docker:
      - image: golang:1.15
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)
workflows:
  build_lint_test:
    jobs:
      - build
      - lint
      - test