version: 2.1
jobs:
  build-app-karsajobs:
    working_directory: ~/go/src/github.com/dicodingacademy/karsajobs
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: 
          name: Build Docker Image
          command: docker build -t ghcr.io/rachmandev/karsajobs:latest .
      - run:
          name: Login to Github
          command: docker login -u rachmandev -p dckr_pat_5SR7jWwo1rkBFWPQWjJ7Uij1nNM
      - run:
          name: Push Image to Github Packages
          command: docker push ghcr.io/rachmandev/karsajobs:latest
  lint-docker:
    docker:
      - image: golangci/golangci-lint:v1.15
    steps:
      - checkout
      - run: 
          name: Run the Linter
          command: golangci-lint -v run
  test-app:
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    docker:
      - image: golang:1.15
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)
workflows:
  build_lint_test:
    jobs:
      - build-app-karsajobs
      - lint-docker
      - test-app