version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.15-alpine
      working_directory: /go/src/github.com/dicodingacademy/karsajobs
      - checkout
      - go install github.com/foo/bar/cmd/baz 

  # golangci-lint runs dozens of linters in parallel on your project. It is the
  # best Go linter.
  lint:
    docker:
      - image: golangci/golangci-lint:v1.37-alpine
    steps:
      - checkout
      - run: golangci-lint run
  test:
    docker:
      # We use golang:1.16 instead of golang:1.16-alpine because we want to run
      # tests with the race detector enabled. The race detector requires glibc,
      # which is only present in the Debian-based containers.
      - image: golang:1.15
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    steps:
      - checkout
      - run: go test -v -race ./...

workflows:
  build_lint_test:
    jobs:
      - build
      - lint
      - test