version: 2.1
jobs:
  build:
    working_directory: ~/go/src/github.com/dicodingacademy/karsajobs
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: 
          name: Build Docker Image
          command: docker build -t ghcr.io/rachmandev/karsajobs:latest .
  lint:
    docker:
      - image: golangci/golangci-lint:latest-alpine
    steps:
      - checkout
      - run: golangci-lint
  test-app:
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    docker:
      - image: golang:1.15
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)
workflows:
  build_lint_test:
    jobs:
      - build
      - lint
      - test-app