version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable

jobs:
  build-app-karsajobs:
    working_directory: ~/go/src/github.com/dicodingacademy/karsajobs
    docker:
      - image: cimg/go:1.15.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: 
          name: Build Docker Image
          command: docker build -t rachmandev/karsajobs:latest .
      - run:
          name: Login to Docker
          command: docker login -u rachmandev -p dckr_pat_DiYRgP-Eqg9NRmzFq3u-7FfypkE
      - run:
          name: Push Image to Docker Hub
          command: docker push rachmandev/karsajobs:latest

  lint-docker:
    executor: docker
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Run hadolint
            command: docker run --rm --interactive hadolint/hadolint < Dockerfile

  test-app:
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    docker:
      - image: golang:1.15
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)
workflows:
  build_lint_test:
    jobs:
      - build-app-karsajobs
      - lint-docker
      - test-app