version: 2.1

jobs:
  build:
    docker:
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
      - image: golang:1.15-alpine
      - checkout
      - go install github.com/foo/bar/cmd/baz 
  lint:
    docker:
      - image: golangci/golangci-lint:v1.37-alpine
    steps:
      - checkout
      - run: golangci-lint run
  test:
    docker:
      - image: golang:1.15
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    steps:
      - checkout
      - run: go test -v -race ./...

workflows:
  build_lint_test:
    jobs:
      - build
      - lint
      - test