apiVersion: v1 # Menggunakan kubernetes api version 1
kind: Namespace #Jenis object kubernetes yang akan dibuat adalah Namespace
metadata: #parameter untuk mendefinisikan object
  name: monitoring #nama object yang akan digunakan
  labels: #labels pada parameter metadata
    app: monitoring #menggunakan label dengan app monitoring