# key name dengan name Build Lint and Test Docker untuk di tampilkan ke actions
name: Build, Lint and Test Docker

# key on dengan nilai push agar saat ada perubahan code action langsung run
on:
  push

jobs: # key Jobs pada github action
  build_and_push_image: # job untuk workflows build_and_publish_image
    name: Build and Publish App Karsajobs #name jobs untuk key build_and_push_image
    runs-on: ubuntu-latest #github action / Docker berjalan pada OS ubuntu terbaru
    steps: #step dari jobs build_and_push_image
      - uses: actions/checkout@v3 # key uses dengan nilai actions/checkout@v3 untuk menjalankan checkout dengan versi 3
      - name: Build Image # key name dengan nilai Build image
        run: docker build -t ghcr.io/rachmandev/karsajobs:latest . # melakukan build docker image dengan tag ghcr.io/rachmandev/karsajobs:latest
      - name: Login to Github # key name dengan nilai Login to Github
        run: docker login --username rachmandev --password ${{ secrets.GithubToken }} ghcr.io #melakukan login ke github untuk push image
      - name: Push Image # key name dengan nilai Push Image
        run: docker push ghcr.io/rachmandev/karsajobs:latest # melakukan push docker image ke github packages

  lint: # jobs untuk workflows lint
    name: Run Lint Hadoline # key name dengan nilai run lint hadoline
    runs-on: ubuntu-latest #github action / lint hadolint berjalan pada OS ubuntu terbaru
    container: pipelinecomponents/hadolint:0.10.1  # key container menjalankan hadolint dengan versi 0.10.1
    steps: # steps untuk lint
      - uses: actions/checkout@v3 # key uses dengan nilai actions/checkout@v3 untuk menjalankan checkout dengan versi 3
      - name: Run hadolint # key name dengan nilai Run Hadolin
        run: hadolint Dockerfile # menjalankan hadolint Dockerfile

  test: # jobs untuk workflows lint
    name: Run Test App Karsajobs # key name dengan nilai Run Test App Karsajobs
    runs-on: ubuntu-latest #github action / test app berjalan pada OS ubuntu terbaru
    steps: # step untuk test
      - uses: actions/checkout@v3 # key uses dengan nilai actions/checkout@v3 untuk menjalankan checkout dengan versi 3
      - name: Test App Karsajobs # key name dengan nilai Test App Karsajobs
        run: go test -v -short --count=1 $(go list ./...)  # menjalan test app karsajobs