name: Build and Lint Docker

on:
  push

jobs:
  build_publish_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cschleiden/actions-linter@v1
      - name: Build Image
        run: docker build -t ghcr.io/rachmandev/karsajobs-ui:latest .
      - name: Login to Github
        run: docker login --username rachmandev --password ${{ secrets.GithubToken }} ghcr.io
      - name: Push Image
        run: docker push ghcr.io/rachmandev/karsajobs-ui:latest
  lint:
    name: Lint Hadoline
    runs-on: ubuntu-latest
    container: pipelinecomponents/hadolint:0.10.1
    steps:
      - uses: actions/checkout@v3
      - name: Run hadolint
        run: hadolint Dockerfile